### ISSUE TITLE
Loyalty bugs.

### ISSUE THREAD

**Issue by ShounPL** [TWLan/Issues#108]
Hello, excuse my bad English, I'am Poland. Bugs in I'am Loyalty  I attacked village in create's. Loyalty loss from 100 to 76 does not fall upon pleased that attacked several times...I used google translator

**Comment by steffengy** [comment]
Google translator generally is not really understandable.
So I do not really understand the problem you have.

Unfortunately we can't help you, if we can't understand the problem.
