### ISSUE TITLE
Language change  bug

### ISSUE THREAD

**Issue by portuges23** [TWLan/Issues#110]
i go to app.json and change language to pt
then the game just stopped while i was seeing ranks
console just says expection:file does not exist:config/language/.json
i think after i change language it when crazy to look for ".json" that doesnt exist i tryed to put back to en but it stayed the same

**Comment by Siguza** [comment]
Mind posting your app.json?

**Comment by portuges23** [comment]
{
    "db": {
        "user": "twlan",
        "password": "peter hat haare",
        "database": "twlan"
    },
    "lang": "en",
    "sidTimeout": 720
}

after i change back to en

**Comment by steffengy** [comment]
If I change the lang to "pt", I get the expected result of a working portuguese startpage.
I cannot reproduce the issue.

**Comment by portuges23** [comment]
i deleted it and extracted again didnt try pt yet do u think it was because i extracted on desktop 1.4 sometimes had that problem?
