### ISSUE TITLE
Worldmap

### ISSUE THREAD

**Issue by SnupW** [TWLan/Issues#113]
The problem is here: htdocs\templates\twlan\controllers\game\map\index.php on line 129-135
<td><?php echo $worldinfo["villages"]; ?></td>
<td><?php echo $worldinfo["barbarians"]; ?></td>
<td><?php echo $worldinfo["barbarians_percentage"]; ?></td>
<td><?php echo $worldinfo["tribe_villages"]; ?></td>
<td><?php echo $worldinfo["tribe_percentage"]; ?></td>
<td><?php echo $worldinfo["own_villages"]; ?></td>
<td><?php echo $worldinfo["own_percentage"]; ?></td>

**Comment by steffengy** [comment]
Will be fixed in the next release. 

internal reference: [upstream](https://bitbucket.org/TWLan/extension/commits/bb66819)
