### ISSUE TITLE
I did Polish language translation

### ISSUE THREAD

**Issue by Qbsoon** [TWLan/Issues#118]
Today I translated all TWLan to polish language using your translation tool.
Can you please see it and add to your download site (on which you have english and deutsch already)?
[pl.zip](https://github.com/TWLan/Issues/files/1126104/pl.zip)
I also added to lang section a line called pl.
And please inform me if you add it or not.

**Comment by 0xEAB** [comment]
Maybe you would like to create a pull request over there: https://github.com/TWLan/Translations

**Comment by Siguza** [comment]
[Merged](https://github.com/TWLan/Translations/commit/27668e645c792193d3b9e243c7585577abf6b0af), thanks. :)

**Comment by Qbsoon** [comment]
I don't know how to. I tried before and when I was there, I clicked on
"base", but I don't know what to write there. I tried translations, pl or
something else, but only working word is "master". When I write there
something else it says "
There isn’t anything to compare.

We couldn’t figure out how to compare these references, do they point to
valid commits?
"

sob., 8 lip 2017 o 10:36 użytkownik Siguza <notifications@github.com>
napisał:

**Comment by Siguza** [comment]
Ehm... it seems you missed my comment. I merged your changes, I accepted your proposed file with [this commit](https://github.com/TWLan/Translations/commit/27668e645c792193d3b9e243c7585577abf6b0af), [it's there now](https://github.com/TWLan/Translations/blob/master/pl.json). :)

**Comment by Qbsoon** [comment]
Yeah, I missed it. Thanks for uploading!

czw., 13 lip 2017 o 16:43 użytkownik Siguza <notifications@github.com>
napisał:
