### ISSUE TITLE
"Resources available" countdown

### ISSUE THREAD

**Issue by Siguza** [TWLan/Issues#60]
This affects:

* Building (should be done?)
* Recruiting (should be done?)
* Researching  (should be done?)
* Academy: Coins (Why does github display this point separately?! :rage: )

- [x] When it takes less than a minute until enough resources are available to, there should be an active countdown which is replaced by a button/form upon hitting zero. (Handled by JS anyways)
- [x] The recruiting screens should at all replace the form if not enough resources are available, instead of just suggesting "(0)" as amount.

**Comment by steffengy** [comment]
What hits 0?
In the main building everything works perfectly.
