### ISSUE TITLE
Eliminate "for ... in range(...)"

### ISSUE THREAD

**Issue by Siguza** [TWLan/Issues#86]
```
for x in range(y, z)
```

This construct essentially creates an array with all values between y and z and iterates over it. That is highly inefficient and every occurrence should be replaced with something like:

```
var x = y;
while x <= z
{
    // ...
    let x = x + 1;
}
````

**Comment by steffengy** [comment]
I am not entirely sure of this, who did you come to that assumption?
In zephir and generated code I couldn't validate it yet.

Will probably take a look at it tomorrow...

**Comment by Siguza** [comment]
Nvm, only happens when you're dumb enough to pass it a non-numeric value. -.-
